---
# output:
#   html_document:
#     toc: true
#     toc_float: true
#     fig_pos: "H"
---

<br>

# Current Projects


## Self-Motion in Microgravity

I was lucky enough to be hired on a project under the lead of Prof. Dr. Laurence Harris, funded by the Canadian Space Agency. In this project we shoot people into orbit and how this affects depth perception and a sense of self-motion generated by visual cues. The main idea is that people should weight visual input more strongly in the absence of gravity. How will everything play out? Tune in in a year or so and we'll let you know!

## Prediction of motion during self-motion

So it seems that humans misperceive the velocity of targets in their environment both less accurately and less precisely when they are moving themselves. (Actually, the debate on this is less settled than I thought at first, but check out our poster at VSS2020 – if it is accepted of course!) But do these changes translate to biases in prediction? It's quite likely that, when we observe motion and judge it incorrectly, then our predictions should reflect these misestimations. But let's find out!


## Do humans have an internal model of Air Drag?

We (kinda) know that humans represent physical information about their environment, e. g. the size of objects they interact with, the gravitational pull on earth, … but is air drag among these physical properties? We think it should be. To be honest, it wouldn’t make much sense if we didn’t … but well, we’re scientists and we need to check!

I am developing this project together with [Borja Aguado](https://osf.io/tj628/) under supervision of Dr. Joan López-Moliner.


## Does earth-gravity conformant motion facilitate motion duration estimation?

It has been shown that earth gravity congruent motion benefitted motion duration estimates for 2D motion in front of a pictorial background. We would expect the same for more naturalistic stimuli (parabolic motion in 3D in a rich environment). And that’s what we’re testing.

I am developing this project together with Dr. Barbara LaScaleia, under supervision of Dr. Myrka Zago.

---