---
output:
#  pdf_document:
#    toc: yes
  html_document:
    fig_pos: H
    includes:
      after_body: _footer.html
    toc: yes
    toc_float: yes
---

<style>
.column-left{
  float: left;
  width: 35%;
  text-align: left;
}


.column-right{
  float: right;
  width: 65%;
  text-align: left;
}
</style>

<br>

If you prefer a PDF version of my CV, press [here](https://github.com/b-jorges/rmarkdown-website-tutorial/raw/gh-pages/CV.pdf) to download.

# CURRICULUM VITAE

<br>

### Personal & Contact Data

<div class="column-left">
Name: <br>
Pronouns: <br>
Resident of: <br>
Telephone: <br>
Email address: <br>
Twitter:<br>
</div>



<div class="column-right">
Björn Jörges <br>
he/him <br>
Toronto, Ontario, Canada <br>
+1 647 550 2495 <br>
[bjoerges@yorku.ca](mailto:bjoerges@yorku.ca) <br>
[b_jorges](https://twitter.com/b_jorges)<br>

</div>

<br>

<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
  .col3 {
    columns: 3 100px;
    -webkit-columns: 3 100px;
    -moz-columns: 3 100px;
  }
</style>



### Education and Academic Positions


<div class="row">
  <div class="col-md-4" markdown ="1">
  From 10/2019:
  </div>
  <div class="col-md-8" markdown ="1">
  PostDoc position at the Center for Vision Research, York University, Toronto, Canada, funded by the Canadian Space Agency
  </div>
</div>

<br>

<div class="row">
  <div class="col-md-4" markdown ="1">
  03/2016 - 09/2019:
  </div>
  <div class="col-md-8" markdown ="1">
  PhD Research position at the Department of Cognition, Development and Psychology of Education, Faculty of Psychology, University of Barcelona in Barcelona, Spain <br>
  Degree awarded: PhD in Cognitive Science and Language "Sobresaliente/Cum Laude"  
  </div>
</div>

<br>


<div class="row">
  <div class="col-md-4" markdown ="1">
  10/2015 – 02/2016:
  </div>
  <div class="col-md-8" markdown ="1">
  Middle European Interdisciplinary Master’s Program in Cognitive Science at University of Vienna in Vienna, Austria <br>
  </div>
</div>

<br>

  
<div class="row">
  <div class="col-md-4" markdown ="1">
  10/2012 – 09/2015:
  </div>
  <div class="col-md-8" markdown ="1">
  Master of Arts in Cognitive Science and Language at University of Barcelona in Barcelona, Spain <br>
Degree awarded: Master of Arts with an average grade of 8.3 (on a scale from “0-4 – Suspended” to “10 – With honors”) 
  </div>
</div>

<br>

<div class="row">
  <div class="col-md-4" markdown ="1">
  09/2008 – 09/2012:
  </div>
  <div class="col-md-8" markdown ="1">
  Bachelor of Arts in Translation Science at University of Heidelberg, with ERASMUS exchanges to Universidad de Pablo de Olavide, Seville, Spain, and Universidad do Porto, Porto, Portugal <br>
Degree awarded: Bachelor of Arts with an average grade of 1.3 (on a scale from “1 – Very good” to “5 – Suspended”) <br>
  </div>
</div>

<br>

### Research focus area

My research is focused on the role of vestibular cues for visual perception and the interaction between self-motion and the visual perception of object motion in our environment.

I have furthermore a strong interest in Philosophy of Science and I am a defender of Open Science practices, as well as a proud member and supporter of the LGBTIQA2S+ community.

<br>

### Publications

Jörges, B., Harris, L. R. (2020). Object speed perception during lateral self-motion. Attention, Perception and Psychophysics. Attention, Perception & Psychophysics. Stage 1 Registered Report (in principle acceptance obtained, data collection pending)

Jörges, B., & López-Moliner, J. (2020). Determining mean and standard deviation of the strong gravity prior through simulations. PLoS ONE 15(8): e0236732. https://doi.org/10.1371/journal.pone.0236732

Jörges, B., & López-Moliner, J. (2019). Earth-gravity congruent motion facilitates ocular control for pursuit of parabolic trajectories. Scientific Reports, 9(1), 1–13. https://doi.org/10.1038/s41598-019-50512-6

Jörges, B., Hagenfeld, L., & López-Moliner, J. (2018). The use of visual cues in gravity judgements on parabolic motion. Vision Research, 149, 47–58. https://doi.org/10.1016/J.VISRES.2018.06.002

Jörges, B., & López-Moliner, J. (2017). Gravity as a strong prior: Implications for perception and action. Frontiers in Human Neuroscience, 11(203). https://doi.org/10.3389/fnhum.2017.00203

<br>

### Conferences and Workshops

Jörges, B., Harris, L. R., (2021, February 16-17) In presence of a visual-vestibular conflict, the visual perception of object velocity is biased and less precise during self-motion [Poster Presentation]. Vestibular Oriented Research Meeting 2021, Virtual Meeting (accepted).

Jörges, B., López-Moliner, J. (2021, January 8) A probabilistic mental representation of earth gravity to predict object motion in our environment [Poster Presentation] LGBTQ+ STEMinar 2021, Virtual Meeting (accepted).

Jörges, B., Bury, N., McManus, M., Allison, R., Jenkin, M., & Harris, L. R. (2020, December 14-17) Sex and/or gender differences in the perception of distance and self-motion [Oral Presentation]. 7th International Symposium on Visually Induced Motion Sensations, Virtual Meeting.

Jörges, B., Bury, N., McManus, M., Allison, R., Jenkin, M., & Harris, L. R. (2020, October 5-7) The perception of visually simulated self-motion is altered by body posture [Data Blitz talk]. 3rd Interdisciplinary Navigation Symposium, Virtual Meeting.

Jörges, B., Bury, N., McManus, M., Allison, R., Jenkin, M., & Harris, L. R. (2020, November 16) The Perception of Travelled Distance in Microgravity [Poster Session]. PRISMA Conference 2020, Universidad Complutense de Madrid, Madrid, Spain & Online.

Jörges, B., Bury, N., McManus, M., Allison, R., Jenkin, M., & Harris, L. R. (2020, August 26 & 28) The Perception of Travelled Distance in Microgravity [Poster Session]. STEM Village Virtual Symposium, Online

Jörges, B. & Harris, L. R. (2020, May 15-20) Incomplete compensation for visual self-motion in the perception of object velocity [Poster Session]. 2020 Annual Meeting of the Vision Science Society, St. Pete’s Beach, Florida, USA (online conference)

Jörges, B. & Harris, L. R. (2020, May 1–3) Incomplete compensation for self-motion in the visual perception of object velocity during a visual-vestibular conflict [Poster Session]. 2020 Vestibular-Oriented Research Meeting, York University, Toronto, Canada (accepted; conference cancelled)

Jörges, B. & Harris, L. R. (2020, January 10) Incomplete compensation for visual self-motion in the perception of object velocity [Poster Session]. LGBTQ+ STEMinar 2020, University of Birmingham, Birmingham, United Kingdom

Jörges, B. & López-Moliner, J. (2019, May 17-22) Earth-Gravity Congruent Motion Facilitates Ocular Control for Pursuit of Parabolic Trajectories [Poster Session]. Vision Science Society, St. Pete’s Beach, Florida, USA

Jörges, B. & López-Moliner, J. (2019, January 11) Earth-Gravity Congruent Motion Facilitates Ocular Control for Pursuit of Parabolic Trajectories [Poster Session]. LGBTQ+ STEMinar, Institute for Physics, London, United Kingdom

Jörges, B. (2018, July 5) Challenges of LGBTQ+ Persons in Academia [Oral Presentation]. LGBTQ+ in STEM Day 2018, University of Barcelona, Barcelona, Spain

Jörges, B., Hagenfeld, L. & López-Moliner, J. (2018, May 18-23) Moderate Influence of Certainty about Target Size on Visual Gravity Judgements [Poster Session]. 2018 Annual Meeting of the Vision Sciences Society, St. Pete Beach, Florida, USA

Jörges, B. & López-Moliner, J. (2017, August 27-31) Decision Variables in Visual Gravity Judgements: Evidence from Simulating the Decision Process [Poster Session]. European Conference on Visual Perception 2017, Berlin, Germany

Jörges, B. (2017, June 22) Nothing New under the Sun: Problem of Induction Still not Solved [Poster Session]. Middle European Interdisciplinary Conference in Cognitive Science 2017, Budapest, Hungary

Jörges, B. & López-Moliner, J. (2017, May 19-24) Temporal derivative of the elevation angle as a cue for visually perceived gravity [Poster Session]. Annual Meeting of the Vision Sciences Society, St. Pete Beach, Florida, USA

Jörges, B. & López-Moliner, J. (2016, November 30 - December 1) Temporal derivative of the elevation angle as a cue for visually perceived gravity [Poster Session]. 2nd PhD Workshop of the Institute of Neuroscience 2016, University of Barcelona, Barcelona, Spain

Jörges, B., Hoogland, D., & Fischer, B. (2016, November 18-19) Do Scientific Convictions Serve as a Buffer against Death Anxiety? [Oral Presentation]. 2016 Workshop on Experimental Philosophy of the Berlin School of Mind and Brain, Berlin, Germany

<br>

### Organizing and Leadership Experience

Member of the Vision Science Society’s Student/Postdoc Advisory Committee (2020–2022)

Director for Research and Conferences in the Spanish Association for LGBTIQA+ Individuals in Science, Technology and Innovation PRISMA (2019–present); activities include:

-	Lead writer on a Whitepaper on the concepts “Sex” and “Gender” and the benefits of so called “Self-ID laws” for transgender people (2020)
-	Lead writer on a grant proposal to study the situation of LGBTIQA+ people working in Science, Technology and Innovation in Spain (2020)
-	Member of the Organizing Committee for PRISMA Conference 2020 on LGBTIQA+ Diversity in Science, Technology and Innovation, November 2020, Madrid, Spain (2019-2020)

Member of the 3rd PhD Workshop of the Institute of Neuroscience (2018) PhD committee at University of Barcelona in Barcelona, Spain

Main Organizer of the 1st LGBTQ+ in STEM Day at University of Barcelona, in Barcelona, Spain (2018)

Member of the 2nd PhD Workshop of the Institute of Neuroscience (2017) PhD committee at University of Barcelona in Barcelona, Spain

Member of the Council of the Department of Cognition, Development and Psychology of Education (2016-2019) at University of Barcelona in Barcelona, Spain

<br>

### Teaching and Mentoring
Mentoring of graduate and undergraduate students (John Kim, Meaghan McManus, Rachel Phan) in the Harrislab, York University, Toronto, Canada (2020)

Practical part of a seminar on Basics of Visual Perception (10-12/2017 and 10-12/2018)

<br>

### Internships, Summer Schools and other Training

Selected participant in 4th Summer School on Statistical Methods for Linguistics and Psychology, Bayesian Inference track, University of Potsdam, Potsdam, Germany (September 7–11 2020)

Attendee at the PsychoPy Workshop, York University, Toronto (2019, November 18)

Attendee at the science advocacy workshop “Standing Up for Science”, Barcelona, Spain (2018, November 30)

PhD Research Internships with Myrka Zago at Santa Lucia Foundation, Rome, Italy, developing a project on motion time discrimination for gravitational parabolic object motion (July–October 2017 and September/October 2018)

<br>

### Funding

Travel Award ACI 2017-2 (400 EUR) issued by the Institute of Neuroscience, University of Barcelona, Spain, for participation in the European Conference for Visual Perception 2018 in Berlin, Germany

PhD scholarship “Ajuts per a la contractació de personal 753 investigador novell (FI-2016)” (14400 EUR/year, plus a 3000 EUR allowance for professional development activities) from the Catalan government for a period of three years (2016 – 2019)

ERASMUS scholarship (600 EUR) for an exchange to Universidade do Porto, Porto, Portugal (2010)

ERASMUS scholarship (480 EUR) for an exchange to Universidad Pablo de Olavide, Seville, Spain (2009/2010)

<br>


### Professional Memberships

[Vision Sciences Society](https://www.visionsciences.org/)

[PRISMA](./PRISMA.html) – Asociación para la Diversidad Afectivo-Sexual y de Género en Ciencia, Tecnología e Innovación

[Out in Science, Technology, Engineering, and Mathematics (oSTEM)](https://www.ostem.org/)

<br>

### Media Appearances
Interview about the importance of queer perspectives in Science, Technology and Innovation [in the Spanish online newspaper “El Salto Diario”](https://www.elsaltodiario.com/paradoja-jevons-ciencia-poder/la-diversidad-en-la-ciencia-espanola) (September 2019)

Author of several publications on the Cognitive Science blog Cognitive.Cat (2014 & 2015)
<br>

### Skills
Languages: German (Native), English/Spanish/Portuguese (near Native), Catalan/Italian (Proficient), French (Basic knowledge)

Data analysis: R (Expert), Julia (Proficient)

Experimental Control Flows: Unity + C# (Expert), Python/PsychoPy (Proficient)

Data Management and Code Versioning: Git/GitHub (Proficient), Open Science Foundation (Competent)

<br>

### Non-Academic Professional Experience
Freelance Translator (English, Spanish and Portuguese into German) for internal and customer-facing business communication, often working with tight deadlines (March 2014 – March 2016), including the German translation of the self-help book “Rewiring the Soul: Finding the Possible Self“ by Gabriella Kortsch, PhD

Foreign Language Specialist, Webmaster and Marketing Writer at Keramik-im-Hof, Salz, Germany (July 2012 – September 2015)

Translation of Portuguese Government Declarations for the Political Economy of Reforms SFB 884, University of Mannheim (December 2010 – August 2011)

<br>

### Further Information
Member of the LGBTIQA2S+ volleyball league Toronto Spartan Volleyball League (starting 2020)

Member of the LGBTQ+ sports organization Panteres Grogues (2013 – 2019) in Barcelona, Spain, including participation as competitive player in the 2nd Division of the Catalan Volleyball League (2016 – 2019)

---
