---
---

<br>

## Publications

Jörges, B., Harris, L.R. Object speed perception during lateral visual self-motion. Atten Percept Psychophys (2021). https://doi.org/10.3758/s13414-021-02372-4

Jörges, B. (2021). Data Analysis and Power Simulations with General Linear Mixed Modelling for Psychophysical Data – A Practical , R-Based Guide. PsyArXiv. https://doi.org/10.31234/osf.io/ack8u

Jörges, B., La Scaleia, B., López-Moliner, J., Lacquaniti, F., & Zago, M. (2021). Perceptual judgments of duration of parabolic motions. Scientific Reports, 11(1), 1–13. https://doi.org/10.1038/s41598-021-86428-3

Jörges, B., & López-Moliner, J. (2020). Determining mean and standard deviation of the strong gravity prior through simulations. PLoS ONE 15(8): e0236732. https://doi.org/10.1371/journal.pone.0236732

Jörges, B., & López-Moliner, J. (2019). Earth-gravity congruent motion facilitates ocular control for pursuit of parabolic trajectories. Scientific Reports, 9(1), 1–13. https://doi.org/10.1038/s41598-019-50512-6

Jörges, B., Hagenfeld, L., & López-Moliner, J. (2018). The use of visual cues in gravity judgements on parabolic motion. Vision Research, 149, 47–58. https://doi.org/10.1016/J.VISRES.2018.06.002

Jörges, B., & López-Moliner, J. (2017). Gravity as a strong prior: Implications for perception and action. Frontiers in Human Neuroscience, 11(203). https://doi.org/10.3389/fnhum.2017.00203

<br>

---